[package]
name = "native-launcher"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
endless-sea = { package = "endless-sea", path = "../.." }
bevy = { version = "0.10.1" }
image = "0.24.6"
winit = "0.27"
